@startuml
class Address {
addressLocales:List<AddressLocale>
priority:String
cityCode:String
addressKey:String
addressId:String
addressInput:String
addressLine1:String
addressLine2:String
addressLine3:String
addressLine4:String
addressLine5:String
addressTypes:List<AddressTypes>
authorizations:List<Authorization>
city:String
citySubdivision:String
country:String
countryCode:String
county:String
countyCode:String
label:String
position:Position
postalCode:String
postalCodeExt:String
preferredIndicator:Boolean
region:String
state:String
locale:String
}
class ControlAccount {
identifiers:List<Identifier>
controlAccountDesc:String
controlAccountId:String
controlAccountKey:String
controlAccountName:String
controlAccountType:ControlAccountTypes
controlTypeId:String
bankAccountId:String
isCounted:Boolean
prefix:String
controlAccountRoleType:ControlAccountRoleTypes
financialCategoryType:FinancialCategoryTypes
}
class Identifier {
identifierId:String
identifierKey:String
context:String
value:String
detail:String
identifierType:String
}
class Part {
partId:String
partKey:String
partConditionGradeType:PartConditionGradeTypes
partConditionType:PartConditionTypes
lastInventoryDate:Date
prices:List<Price>
partLifecycles:List<PartLifecycle>
partStatusType:PartStatusTypes
identifiers:List<Identifier>
partIdentifiers:List<PartIdentifier>
controlAccount:ControlAccount
partStatusTypes:List<PartStatusTypes>
partEvents:List<PartEvent>
warehouse:Warehouse
partLocation:PartLocation
}
class PartEvent {
partEventKey:String
partEventId:String
occurrenceDateTime:Date
actorId:String
actorName:String
actorHref:String
eventCategory:String
eventLabel:String
partInventoryActionType:PartInventoryOrderTypes
partStatusType:PartStatusTypes
version:String
effectiveDate:Date
}
class PartIdentifier {
partIdentifierKey:String
partIdentifierId:String
partIdentifierType:PartIdentifierTypes
partIdentifierValue:String
description:String
identifiers:List<Identifier>
partNames:List<PartName>
}
class PartLifecycle {
partLifecycleId:String
partLifecycleKey:String
isSuperseded:Boolean
reason:String
partStatusTypes:List<PartStatusTypes>
superSessions:List<SuperSession>
}
class PartLocation {
warehouse:Warehouse
partStorageTypes:PartStorageTypes
aisle:String
rack:String
shelf:String
bin:String
quantity:Integer
}
class PartName {
partNameId:String
partNameKey:String
description:String
partNameType:PartNameTypes
}
class Price {
displayValue:String
locale:String
value:String
priceKey:String
taxIncludedIndicator:Boolean
currencyCode:String
priceId:String
endDate:Date
effectiveDate:Date
priceTypes:List<PriceTypes>
}
class SuperSession {
prevPartNames:List<PartName>
newPartNames:List<PartName>
partOrderConfigType:PartOrderConfigTypes
quantity:String
productConsumptionType:ProductConsumptionTypes
warehouses:List<Warehouse>
productStageType:ProductStageTypes
partyIdentifiers:List<PartyIdentifier>
partStatusTypes:List<PartStatusTypes>
}
class Warehouse {
warehouseId:String
warehouseKey:String
warehouseCode:String
warehouseName:String
partyId:String
identifiers:List<Identifier>
warehouseTypes:List<WarehouseTypes>
addresses:List<Address>
}
class AddressTypes #FAFF91 {
ARCHIVE
AR_ADDRESS
BILLING
BUSINESS
CONTRACT
CURRENT
DEALER
DELIVERY
DESTINATION
EMERGENCY
GARAGE
HOME
INSURANCE
LEGAL
MAILING
ORIGINAL
OTHER
POSTAL
PREVIOUS
PRODUCT
REBATE
RECIPIENT
RESIDENCE
SERVICE
SERVICE_CONTRACT
SHIPPING
TEMPORARY
VACATION
WORK
}
class ControlAccountRoleTypes #FAFF91 {
MASTER
OTHER
SPLIT
STANDARD
SUB
}
class ControlAccountTypes #FAFF91 {
ACCESSORIES
ASSETS
CLEARING
COGS
CONTRA_ASSET
CREDIT
CUSTOMER
DEALER
DEPRECIATION
DISCOUNT
EMPLOYEE
EQUITY
EXPENSE
FEE
FIXED_ASSETS
LIABILITY
LONG_TERM_LIABILITY
OPTION
OTHER
OTHER_INCOME
PACKAGE
PARTS_SALES_ORDER
PRODUCT
PROVISION
REBATE
REFERENCE
REPAIR_ORDER
REVENUE
ROUNDING
SERVICE
TAX
VEHICLE
VENDOR
}
class FinancialCategoryTypes #FAFF91 {
CAPEX
HARDWARE
MAINTENANCE
OPEX
OTHER
RENT
REVENUE
SALARY
SOFTWARE
TAX
TRAINING
TRAVEL
UTILITIES
}
class PartConditionGradeTypes #FAFF91 {
ACCEPTABLE
DAMAGED
EXCELLENT
FAIR
GOOD
LIKE_NEW
OTHER
POOR
UNGRADED
VERY_GOOD
}
class PartConditionTypes #FAFF91 {
COLLECTIBLE
DAMAGED_COSMETIC
DAMAGED_MINOR
NEW
NEW_OLD_STOCK
OTHER
REBUILT
REFURBISHED
REMANUFACTURED
SALVAGE
SCRAP
USED
}
class PartIdentifierTypes #FAFF91 {
ALT_CODE
CATALOG_CODE
CONFIG_CODE
COUNTRY_OF_ORIGIN_CODE
ENGINE_CODE
ISBN
MAKE_CODE
MARKET_DIVISION_CODE
MFR_CODE
MODEL_CODE
MPN
NAME
NUMBER
OTHER
PREFIX
PRODUCT_CODE
SKU
STOCK_NBR
STYLE_CODE
SUB_MODEL_CODE
TRANSMISSION_CODE
TRIM_CODE
UNIV_CODE
UPCA
UPCE
VIN
YEAR_CODE
}
class PartInventoryOrderTypes #FAFF91 {
ALLOCATE_RESERVE
BACK_ORDERED
CANCELLED
CONSOLIDATE_INVENTORY
CYCLE_COUNT
DELIVERED
DISPOSITION
INBOUND
LOCATE
MAINTENANCE
NO_LONGER_AVAILABLE
ORDER_FULFILLMENT
OUTBOUND
PENDING
PRE_ORDER
PROCESSING
RECEIVING
RELOCATE
REPLENISH
RETURNED_ORDER
RETURNS_ACTIONS
REVERSE_LOGISTICS
SHIPPED
STOCK_ROTATION
STORAGE
WAREHOUSE_MANAGEMENT
}
class PartNameTypes #FAFF91 {
AFTERMARKET
CORE
GENERIC
MANUFACTURING
MARKETING
OEM
REMANUFACTURING
SUPERSEDED
SUPERSEDING
}
class PartOrderConfigTypes #FAFF91 {
MULTIPLE_MERGE
MULTIPLE_SPLIT
NOT_AVAILABLE
SINGLE
VARIABLE_MERGE
VARIABLE_SPLIT
}
class PartStatusTypes #FAFF91 {
CROSS_DOCK
DISASSEMBLE
DOCUMENT_RECEIPT
DOCUMENT_SHIPMENT
INSPECT_INBOUND
KIT_ASSEMBLE
LABEL_TAG
LOAD_SHIPMENT
PACK
PICK
PUTAWAY
QUARANTINE_INBOUND
RECEIVE
REFURBISH_REPAIR
RETURN_INSPECT
RETURN_PUTAWAY
RETURN_RECEIVE
SCRAP_DISPOSE
SHIP
STAGE_SHIPMENT
SUPERSEDE
SUPERSEDED
VALUE_ADDED_SERVICE
}
class PartStorageTypes #FAFF91 {
BIN
CABINET
CAGE
CONTAINER
CUSTOM
DRAWER
FLOOR
PALLET
RACK
SHELF
}
class PriceTypes #FAFF91 {
ACTUAL
AFFILIATE
BUNDLE
CONTRACT
CORE
CUSTOM
CUSTOMER
DEALER
DISCOUNT
ESTIMATED
FLAT
ITEMIZED
LANDED
LICENSED
LIST
LOCATION
METERED
MONEY
MSRP
NET
ONLINE
OTHER
PERCENT
PER_UNIT
PROMOTIONAL
PURCHASE
QUANTITY
REGION
RETAIL
SALE
SEAT
STAIR_STEP
STANDARD
STORE
SUBSCRIPTION
TIER_GRADUATED
TIER_VOLUME
TRADE
USAGE
VOLUME
WHOLESALE
}
class ProductConsumptionTypes #FAFF91 {
PRE_PRODUCTION
SCRAP_STRATEGY
USE_UP_STRATEGY
}
class ProductStageTypes #FAFF91 {
ACTIVE
DAMAGED
DECOMMISSIONED
DISCONTINUED
FINAL_SUPERSESSION
OBSOLETE
PENDING_APPROVAL
PENDING_OBSOLESCENCE
PHASED_OUT
PRELIMINARY_SUPERSESSION
PRE_PRODUCTION
PRE_RELEASE
PROPOSED
RECALLED
SOURCING_CHALLENGE
UNDER_REVIEW
}
class WarehouseTypes #FAFF91 {
ACCESSORY_WAREHOUSE
AFTERMARKET_SUPPLIER
BODY_SHOP_WAREHOUSE
DEALERSHIP
DISTRIBUTOR
IN_HOUSE_PARTS_STORAGE
MOBILE_PARTS_UNIT
NATIONAL_DISTRIBUTION_CENTER
OEM_WAREHOUSE
OTHER
PARTS_SUPPLIER
REGIONAL_DISTRIBUTION_CENTER
RETURN_CORE_CENTER
THIRD_PARTY_LOGISTICS
TIRES_ONLY_DISTRIBUTION
USED_PARTS_YARD
}
AddressTypes *-- Address
Address *-- Warehouse
ControlAccount -- Part
ControlAccountRoleTypes -- ControlAccount
ControlAccountTypes -- ControlAccount
FinancialCategoryTypes -- ControlAccount
Identifier *-- ControlAccount
Identifier *-- Part
Identifier *-- PartIdentifier
Identifier *-- Warehouse
PartConditionGradeTypes -- Part
PartConditionTypes -- Part
PartEvent *-- Part
PartIdentifierTypes -- PartIdentifier
PartIdentifier *-- Part
PartInventoryOrderTypes -- PartEvent
PartLifecycle *-- Part
PartLocation -- Part
PartNameTypes -- PartName
PartName *-- PartIdentifier
PartName *-- SuperSession
PartOrderConfigTypes -- SuperSession
PartStatusTypes *-- Part
PartStatusTypes *-- PartLifecycle
PartStatusTypes *-- SuperSession
PartStatusTypes -- Part
PartStatusTypes -- PartEvent
PartStorageTypes -- PartLocation
PriceTypes *-- Price
Price *-- Part
ProductConsumptionTypes -- SuperSession
ProductStageTypes -- SuperSession
SuperSession *-- PartLifecycle
Warehouse -- Part
Warehouse -- PartLocation
WarehouseTypes *-- Warehouse
Warehouse *-- SuperSession
@enduml
