@startuml
rectangle "Address" as Address
rectangle "ControlAccount" as ControlAccount
rectangle "Identifier" as Identifier
rectangle "Part" as Part
rectangle "PartEvent" as PartEvent
rectangle "PartIdentifier" as PartIdentifier
rectangle "PartLifecycle" as PartLifecycle
rectangle "PartLocation" as PartLocation
rectangle "PartName" as PartName
rectangle "Price" as Price
rectangle "SuperSession" as SuperSession
rectangle "Warehouse" as Warehouse
rectangle "AddressTypes" as AddressTypes #FAFF91
rectangle "ControlAccountRoleTypes" as ControlAccountRoleTypes #FAFF91
rectangle "ControlAccountTypes" as ControlAccountTypes #FAFF91
rectangle "FinancialCategoryTypes" as FinancialCategoryTypes #FAFF91
rectangle "PartConditionGradeTypes" as PartConditionGradeTypes #FAFF91
rectangle "PartConditionTypes" as PartConditionTypes #FAFF91
rectangle "PartIdentifierTypes" as PartIdentifierTypes #FAFF91
rectangle "PartInventoryOrderTypes" as PartInventoryOrderTypes #FAFF91
rectangle "PartNameTypes" as PartNameTypes #FAFF91
rectangle "PartOrderConfigTypes" as PartOrderConfigTypes #FAFF91
rectangle "PartStatusTypes" as PartStatusTypes #FAFF91
rectangle "PartStorageTypes" as PartStorageTypes #FAFF91
rectangle "PriceTypes" as PriceTypes #FAFF91
rectangle "ProductConsumptionTypes" as ProductConsumptionTypes #FAFF91
rectangle "ProductStageTypes" as ProductStageTypes #FAFF91
rectangle "WarehouseTypes" as WarehouseTypes #FAFF91
AddressTypes *-- Address
Address *-- Warehouse
ControlAccount -- Part
ControlAccountRoleTypes -- ControlAccount
ControlAccountTypes -- ControlAccount
FinancialCategoryTypes -- ControlAccount
Identifier *-- ControlAccount
Identifier *-- Part
Identifier *-- PartIdentifier
Identifier *-- Warehouse
PartConditionGradeTypes -- Part
PartConditionTypes -- Part
PartEvent *-- Part
PartIdentifierTypes -- PartIdentifier
PartIdentifier *-- Part
PartInventoryOrderTypes -- PartEvent
PartLifecycle *-- Part
PartLocation -- Part
PartNameTypes -- PartName
PartName *-- PartIdentifier
PartName *-- SuperSession
PartOrderConfigTypes -- SuperSession
PartStatusTypes *-- Part
PartStatusTypes *-- PartLifecycle
PartStatusTypes *-- SuperSession
PartStatusTypes -- Part
PartStatusTypes -- PartEvent
PartStorageTypes -- PartLocation
PriceTypes *-- Price
Price *-- Part
ProductConsumptionTypes -- SuperSession
ProductStageTypes -- SuperSession
SuperSession *-- PartLifecycle
Warehouse -- Part
Warehouse -- PartLocation
WarehouseTypes *-- Warehouse
Warehouse *-- SuperSession
@enduml
