PariparInviS@startuml

skinparam packageStyle rectangle
skinparam roundcorner 10
skinparam defaultFontName Arial
skinparam componentStyle rectangle

title Automotive Retail Part Domain Map

' --------------------------------------------------------------------------
' LEVEL 1: Identity and Core Reference
' --------------------------------------------------------------------------


 

' --------------------------------------------------------------------------
' LEVEL 2: Core Assets and Operations
' --------------------------------------------------------------------------




package "4. Service, Repair & Parts" as SRP #AAFFDD {
    component "Service Order (AR)" as SORepairAR
    component "Part (AR)" as PartAR
    component "Repair Order (AR)" as RepairOrderAR 
    component "Service Advisory/Receipt Ack. (AR)" as ServiceAdvisoryAR  
    component "Service Appointment (AR)" as ServiceAppointmentAR 
    component "Service Appointment Ack. (AR)" as ServiceAppointmentAckAR 
    component "Service Plan (AR)" as ServicePlanAR 
    component "Service Processing Advisory (AR)" as ServiceProcessAdvAR 
    component "Vehicle Service History (AR)" as VehicleServiceHistoryAR 
    component "Labor Operations (AR)" as LaborOperationsAR 
    component "Monthly Workshop Report (AR)" as WorkshopReportAR 
    component "Parts Activity (AR)" as PartsActivityAR 
    component "Parts Delivery Details (AR)" as PartsDeliveryDetailsAR 
    component "Parts Disposition (AR)" as PartsDispositionAR 
    component "Parts Inventory (AR)" as PartsInventoryAR 
    component "Parts Locator (AR)" as PartsLocatorAR 
    component "Parts Master (AR)" as PartsMasterAR 
    component "Parts Order (AR)" as PartsOrderAR 
    component "Parts Pick List (AR)" as PartsPickListAR
    component "Part Search Criteria (AR)" as PartSearchCriteriaAR
    component "Parts Price List (AR)" as PartsPriceListAR 
    component "Parts Return (AR)" as PartsReturnAR 
}





@enduml