@startuml
class EffectivePeriod {
effectivePeriodKey:String
activeIndicator:Boolean
exclusiveIndicator:Boolean
startDateTime:Date
completeDateTime:Date
durationUomType:DurationUOMTypes
durationValue:String
recurUomType:DurationUOMTypes
recurCount:String
recurCriteria:String
recurIndicator:Boolean
timeslot:TimeSlot
}
class Identifier {
identifierId:String
identifierKey:String
context:String
value:String
detail:String
identifierType:String
}
class LifecycleEvent {
lifecycleEventId:String
lifecycleEventKey:String
actorHref:String
actorId:String
actorName:String
lifecycleEventType:LifecycleEventTypes
occurrenceDate:Date
resourceHref:String
resourceIdentifier:String
detailName:String
detailDesc:String
detailValue:String
detailKey:String
detailCode:String
}
class PartyIdentifier {
partyIdentifierId:String
partyIdentifierKey:String
partyKey:String
partyIdentifierType:String
context:String
partyRelationshipTypes:List<PartyRelationshipTypes>
party:Identifier
occurrenceDateTime:Date
duration:EffectivePeriod
}
class Price {
displayValue:String
locale:String
value:String
priceKey:String
taxIncludedIndicator:Boolean
currencyCode:String
priceId:String
endDate:Date
effectiveDate:Date
priceTypes:List<PriceTypes>
}
class PriceList {
priceListId:String
priceListKey:String
priceDescription:String
productSchedules:List<Identifier>
lifecycleEventType:LifecycleEventTypes
priceSensitivity:PriceSensitivity
priceClassTypes:List<PriceClassTypes>
locale:String
currency:String
financialSplits:List<Identifier>
price:Price
partyIdentifiers:List<PartyIdentifier>
geographicBoundaries:List<Identifier>
priceGroup:List<Identifier>
productGroup:List<Identifier>
priceTypes:List<PriceTypes>
priceUnitDetail:List<Identifier>
priceUsageDetail:List<Identifier>
priceTaxFinance:List<Identifier>
priceTiers:List<Identifier>
lifecycleEvents:List<LifecycleEvent>
partNames:List<Identifier>
partIdentifiers:List<Identifier>
}
class PriceSensitivity {
priceSensitivityId:String
priceSensitivityKey:String
sensitivityLevelTypes:PriceSensitivityTypes
quantityLevelTypes:PriceSensitivityTypes
description:String
}
class DurationUOMTypes #FAFF91 {
BI_WEEKS
CUSTOM
DAYS
DAY_OF_MONTH
HOURS
MINUTES
MONTHS
MULTI_YEARS
NONE
OCCURRENCE
OTHER
QUARTERS
SEMI_MONTHS
SEMI_YEARS
UNLIMITED
WEEKS
YEARS
}
class LifecycleEventTypes #FAFF91 {
ACCESS_ALLOWED
ACCESS_DENIED
CANCELLED
CLOSED
CREATED
DEAD
DELETE_HARD
DELETE_SOFT
FAILED
INITIALIZED
INITIALIZING
PROCESSED
PROCESSING
QUALIFIED
SUBMITTED
UPDATED
VALIDATED
}
class PartyRelationshipTypes #FAFF91 {
ACCOUNTABLE
ACQUAINTANCE
ACTOR
ADVISOR_CONSULTANT
AFFILIATE
AGENT
ASSOCIATE
AUDITOR
BENEFICIARY
BRANCH
BUSINESS_PARTNER
BUYER
CAREGIVER
CHILD
COMPOSED_IN
CONSULT
CONTRACTOR
CORPORATION
COST_CENTER
CO_SIGNER
CO_WORKER
CREDIT_CARD_PROVIDER
CUSTODIAN
CUSTOMER
DEALERSHIP
DEPARTMENT
DEPENDENT
DISTRIBUTOR
DIVISION
EMERGENCY_CONTACT
EMPLOYEE
EMPLOYER
EXECUTE
EX_SPOUSE
FAMILY_MEMBER
FINANCIAL_ADVISOR
FRANCHISE
FREIGHT_FORWARDER
FRIEND
GIFT_TO
GOVERNMENT_AGENCY
GROUP
GUARANTOR
HEIR
INSURED
INSURER
INTERNAL_ORGANIZATION
INVESTOR
JOINT_VENTURE
LEGAL_GUARDIAN
LESSEE
LESSOR
LOAN_PROVIDER
MANAGER
MANUFACTURER
MEMBERSHIP
MENTEE
MENTOR
NON_PROFIT
NOTIFY
OTHER
OTHER_FAMILY
OWNER
PARENT
PARTNER_ORGANIZATION
PART_OF
PAYEE
PAYER
POLITICAL_AFFILIATE
PROFESSIONAL_CONTACT
PROXY
RECIPIENT
REFERENCE_PERSONAL
REFERENCE_PROFESSIONAL
REGULATOR
REMOVE
RESPONSIBLE
ROMANTIC_PARTNER
SECTION
SELF
SERVICE_CONSUMER
SERVICE_PROVIDER
SHAREHOLDER
SHIP_TO
SIBLING
SOLD_TO
SPOUSE
STORE
SUBSIDIARY
SUPPLIER
TEAM
THIRD_PARTY
TRANSACTION_FROM
TRANSACTION_TO
TRUSTEE_PERSON
UNDERWRITER
VENDOR
}
class PriceClassTypes #FAFF91 {
APPROVED
CALCULATED_COST
CHARGE_AMOUNT
COMMERCIAL_COST
CO_INSURANCE
CO_PAYMENT
DEDUCTIBLE
DIRECT_COST
EDUCATIONAL
ENTERPRISE
EXPENSE
EXPENSE_COST
GOVERNMENT
HANDLING
INDIRECT_COST
INVOICE
LABOR_COST
LOYALTY_MEMBER
MATERIAL_COST
MSRP
NEW_CUSTOMER
OFFER
OTHER
PAID
PARTS_COST
PERCENTAGE
PRODUCTION_COST
PRORATED
REFUND
REQUESTED
RETAIL
SCHEDULE
SERVICE_COST
SOLD_PRICE
SUBLET_CHARGE
SUB_TOTAL
TOTAL
TRANSFER_COST
}
class PriceSensitivityTypes #FAFF91 {
ELASTIC
HIGH
INELASTIC
LOW
MEDIUM
}
class PriceTypes #FAFF91 {
ACTUAL
AFFILIATE
BUNDLE
CONTRACT
CORE
CUSTOM
CUSTOMER
DEALER
DISCOUNT
ESTIMATED
FLAT
ITEMIZED
LANDED
LICENSED
LIST
LOCATION
METERED
MONEY
MSRP
NET
ONLINE
OTHER
PERCENT
PER_UNIT
PROMOTIONAL
PURCHASE
QUANTITY
REGION
RETAIL
SALE
SEAT
STAIR_STEP
STANDARD
STORE
SUBSCRIPTION
TIER_GRADUATED
TIER_VOLUME
TRADE
USAGE
VOLUME
WHOLESALE
}
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- PartyIdentifier
Identifier -- PartyIdentifier
Identifier *-- PriceList
LifecycleEventTypes -- LifecycleEvent
LifecycleEventTypes -- PriceList
LifecycleEvent *-- PriceList
PartyIdentifier *-- PriceList
PartyRelationshipTypes *-- PartyIdentifier
Price -- PriceList
PriceClassTypes *-- PriceList
PriceSensitivity -- PriceList
PriceSensitivityTypes -- PriceSensitivity
PriceTypes *-- Price
PriceTypes *-- PriceList
@enduml
