@startuml
rectangle "EffectivePeriod" as EffectivePeriod
rectangle "Identifier" as Identifier
rectangle "LifecycleEvent" as LifecycleEvent
rectangle "PartyIdentifier" as PartyIdentifier
rectangle "Price" as Price
rectangle "PriceList" as PriceList
rectangle "PriceSensitivity" as PriceSensitivity
rectangle "DurationUOMTypes" as DurationUOMTypes #FAFF91
rectangle "LifecycleEventTypes" as LifecycleEventTypes #FAFF91
rectangle "PartyRelationshipTypes" as PartyRelationshipTypes #FAFF91
rectangle "PriceClassTypes" as PriceClassTypes #FAFF91
rectangle "PriceSensitivityTypes" as PriceSensitivityTypes #FAFF91
rectangle "PriceTypes" as PriceTypes #FAFF91
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- PartyIdentifier
Identifier -- PartyIdentifier
Identifier *-- PriceList
LifecycleEventTypes -- LifecycleEvent
LifecycleEventTypes -- PriceList
LifecycleEvent *-- PriceList
PartyIdentifier *-- PriceList
PartyRelationshipTypes *-- PartyIdentifier
Price -- PriceList
PriceClassTypes *-- PriceList
PriceSensitivity -- PriceList
PriceSensitivityTypes -- PriceSensitivity
PriceTypes *-- Price
PriceTypes *-- PriceList
@enduml
