@startuml
class BillOfMaterial {
billOfMaterialKey:String
billOfMaterialId:String
identifiers:List<PartIdentifier>
productIdentifier:String
revision:String
effectiveDate:Date
productStatusType:ProductStatusTypes
components:List<BomComponent>
specification:PartSpecification
}
class BomComponent {
bomComponentId:String
bomComponentKey:String
quantity:String
textualDetails:List<TextualDetail>
componentSpecification:PartSpecification
componentIdentifiers:List<PartIdentifier>
revision:String
effectivePeriod:EffectivePeriod
productStatusType:ProductStatusTypes
}
class EffectivePeriod {
effectivePeriodKey:String
activeIndicator:Boolean
exclusiveIndicator:Boolean
startDateTime:Date
completeDateTime:Date
durationUomType:DurationUOMTypes
durationValue:String
recurUomType:DurationUOMTypes
recurCount:String
recurCriteria:String
recurIndicator:Boolean
timeslot:TimeSlot
}
class Identifier {
identifierId:String
identifierKey:String
context:String
value:String
detail:String
identifierType:String
}
class PartIdentifier {
partIdentifierKey:String
partIdentifierId:String
partIdentifierType:PartIdentifierTypes
partIdentifierValue:String
description:String
identifiers:List<Identifier>
partNames:List<PartName>
}
class PartName {
partNameId:String
partNameKey:String
description:String
partNameType:PartNameTypes
}
class PartSpecification {
partNameType:PartNameTypes
partConditionTypes:List<PartConditionTypes>
partConditionGradeTypes:List<PartConditionGradeTypes>
unitOfMeasures:List<UnitOfMeasure>
identifiers:List<Identifier>
minimumOrderQuantity:Integer
fixedOrderQuantity:Integer
packageQuantity:Integer
itemQuantity:Integer
productPackageType:ProductPackageTypes
}
class TextualDetail {
textualDetailKey:String
textualDetailId:String
shortDescription:String
textKey:String
name:String
value:String
identifiers:List<Identifier>
label:String
altText:String
textualDetailCode:String
uomDisplay:String
uomCode:String
}
class UnitOfMeasure {
unitOfMeasure:EnumBase
uomValue:String
quantity:String
uomQuantityCategoryType:UOMQuantityCategoryTypes
}
class DurationUOMTypes #FAFF91 {
BI_WEEKS
CUSTOM
DAYS
DAY_OF_MONTH
HOURS
MINUTES
MONTHS
MULTI_YEARS
NONE
OCCURRENCE
OTHER
QUARTERS
SEMI_MONTHS
SEMI_YEARS
UNLIMITED
WEEKS
YEARS
}
class PartConditionGradeTypes #FAFF91 {
ACCEPTABLE
DAMAGED
EXCELLENT
FAIR
GOOD
LIKE_NEW
OTHER
POOR
UNGRADED
VERY_GOOD
}
class PartConditionTypes #FAFF91 {
COLLECTIBLE
DAMAGED_COSMETIC
DAMAGED_MINOR
NEW
NEW_OLD_STOCK
OTHER
REBUILT
REFURBISHED
REMANUFACTURED
SALVAGE
SCRAP
USED
}
class PartIdentifierTypes #FAFF91 {
ALT_CODE
CATALOG_CODE
CONFIG_CODE
COUNTRY_OF_ORIGIN_CODE
ENGINE_CODE
ISBN
MAKE_CODE
MARKET_DIVISION_CODE
MFR_CODE
MODEL_CODE
MPN
NAME
NUMBER
OTHER
PREFIX
PRODUCT_CODE
SKU
STOCK_NBR
STYLE_CODE
SUB_MODEL_CODE
TRANSMISSION_CODE
TRIM_CODE
UNIV_CODE
UPCA
UPCE
VIN
YEAR_CODE
}
class PartNameTypes #FAFF91 {
AFTERMARKET
CORE
GENERIC
MANUFACTURING
MARKETING
OEM
REMANUFACTURING
SUPERSEDED
SUPERSEDING
}
class ProductPackageTypes #FAFF91 {
BUNDLE
CASE
COMPONENT
EACH
GROUP
ITEM
KIT
MIXED_BUNDLE
OCCURRENCE
PACK
PALLET
PRODUCT
PURE_BUNDLE
SERVICE
SET
SKU
STANDALONE
SUBSCRIPTION
UNIT
}
class ProductStatusTypes #FAFF91 {
ACTIVE
CANCELLED
DRAFT
OBSOLETE
PENDING
PILOT
RETIRED
REVIEW
SUSPENDED
TERMINATED
UNAVAILABLE
}
class UOMQuantityCategoryTypes #FAFF91 {
COUNT
DEFAULT_LEAD_TIME
DIMENSIONAL_WEIGHT
DIMENSIONS
DIMENSION_UNIT
ELECTRICAL_RATING
GROSS_VOLUME
GROSS_WEIGHT
MATERIAL
MAX_HEIGHT
MAX_LEAD_TIME
MAX_LENGTH
MAX_ORDER_QUANTITY
MAX_WEIGHT
MAX_WIDTH
MIN_HEIGHT
MIN_LENGTH
MIN_ORDER_AVAILABLE
MIN_ORDER_QUANTITY
MIN_WEIGHT
MIN_WIDTH
NET_VOLUME
NET_WEIGHT
PACKAGE_QUANTITY
SHIPPING_WEIGHT
TIME
VOLUME
WEIGHT
}
BomComponent *-- BillOfMaterial
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- BomComponent
Identifier *-- PartIdentifier
Identifier *-- PartSpecification
Identifier *-- TextualDetail
PartConditionGradeTypes *-- PartSpecification
PartConditionTypes *-- PartSpecification
PartIdentifierTypes -- PartIdentifier
PartIdentifier *-- BillOfMaterial
PartIdentifier *-- BomComponent
PartNameTypes -- PartName
PartNameTypes -- PartSpecification
PartName *-- PartIdentifier
PartSpecification -- BillOfMaterial
PartSpecification -- BomComponent
ProductPackageTypes -- PartSpecification
ProductStatusTypes -- BillOfMaterial
ProductStatusTypes -- BomComponent
TextualDetail *-- BomComponent
UOMQuantityCategoryTypes -- UnitOfMeasure
UnitOfMeasure *-- PartSpecification
@enduml
