@startuml
rectangle "BillOfMaterial" as BillOfMaterial
rectangle "BomComponent" as BomComponent
rectangle "EffectivePeriod" as EffectivePeriod
rectangle "Identifier" as Identifier
rectangle "PartIdentifier" as PartIdentifier
rectangle "PartName" as PartName
rectangle "PartSpecification" as PartSpecification
rectangle "TextualDetail" as TextualDetail
rectangle "UnitOfMeasure" as UnitOfMeasure
rectangle "DurationUOMTypes" as DurationUOMTypes #FAFF91
rectangle "PartConditionGradeTypes" as PartConditionGradeTypes #FAFF91
rectangle "PartConditionTypes" as PartConditionTypes #FAFF91
rectangle "PartIdentifierTypes" as PartIdentifierTypes #FAFF91
rectangle "PartNameTypes" as PartNameTypes #FAFF91
rectangle "ProductPackageTypes" as ProductPackageTypes #FAFF91
rectangle "ProductStatusTypes" as ProductStatusTypes #FAFF91
rectangle "UOMQuantityCategoryTypes" as UOMQuantityCategoryTypes #FAFF91
BomComponent *-- BillOfMaterial
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- BomComponent
Identifier *-- PartIdentifier
Identifier *-- PartSpecification
Identifier *-- TextualDetail
PartConditionGradeTypes *-- PartSpecification
PartConditionTypes *-- PartSpecification
PartIdentifierTypes -- PartIdentifier
PartIdentifier *-- BillOfMaterial
PartIdentifier *-- BomComponent
PartNameTypes -- PartName
PartNameTypes -- PartSpecification
PartName *-- PartIdentifier
PartSpecification -- BillOfMaterial
PartSpecification -- BomComponent
ProductPackageTypes -- PartSpecification
ProductStatusTypes -- BillOfMaterial
ProductStatusTypes -- BomComponent
TextualDetail *-- BomComponent
UOMQuantityCategoryTypes -- UnitOfMeasure
UnitOfMeasure *-- PartSpecification
@enduml
