@startuml
class AdvanceSearchValue {
searchType:AdvanceSearchTypes
value:String
}
class AdvancedSearchCriteria {
customTags:List<Identifier>
fuzzySearchEnabled:Boolean
partMasterStatusTypes:List<ProductStageTypes>
includeAssemblyComponents:Boolean
imageSearchConfidenceThreshold:String
advancedSearchValues:List<AdvanceSearchValue>
}
class EffectivePeriod {
effectivePeriodKey:String
activeIndicator:Boolean
exclusiveIndicator:Boolean
startDateTime:Date
completeDateTime:Date
durationUomType:DurationUOMTypes
durationValue:String
recurUomType:DurationUOMTypes
recurCount:String
recurCriteria:String
recurIndicator:Boolean
timeslot:TimeSlot
}
class Identifier {
identifierId:String
identifierKey:String
context:String
value:String
detail:String
identifierType:String
}
class PartIdentifier {
partIdentifierKey:String
partIdentifierId:String
partIdentifierType:PartIdentifierTypes
partIdentifierValue:String
description:String
identifiers:List<Identifier>
partNames:List<PartName>
}
class PartLifecycle {
partLifecycleId:String
partLifecycleKey:String
isSuperseded:Boolean
reason:String
partStatusTypes:List<PartStatusTypes>
superSessions:List<SuperSession>
}
class PartLogisticsCriteria {
warehouseTypes:List<WarehouseTypes>
originLatitude:Double
originLongitude:Double
estimatedAvailabilityDateRange:EffectivePeriod
shippingMethodType:List<ShippingMethodTypes>
requiresPickup:Boolean
warehouses:List<Identifier>
}
class PartName {
partNameId:String
partNameKey:String
description:String
partNameType:PartNameTypes
}
class PartPriceCriteria {
minPrice:String
maxPrice:String
currency:String
coreChargeApplicable:Boolean
warrantyTypes:List<WarrantyTypes>
priceTypes:List<PriceTypes>
}
class PartSearchCriteria {
partSearchCriteriaId:String
partSearchCriteriaKey:String
partIdentifiers:List<PartIdentifier>
partNames:List<PartName>
partConditionType:PartConditionTypes
partConditionGradeType:PartConditionGradeTypes
partPriceCriteria:PartPriceCriteria
partSpecificationCriterias:List<PartSpecification>
partLogisticsCriteria:PartLogisticsCriteria
partLifecycles:List<PartLifecycle>
partStatusTypes:List<PartStatusTypes>
partInventoryActionTypes:List<PartInventoryOrderTypes>
partMasterActionTypes:List<ProductStageTypes>
advancedSearch:AdvancedSearchCriteria
}
class PartSpecification {
partNameType:PartNameTypes
partConditionTypes:List<PartConditionTypes>
partConditionGradeTypes:List<PartConditionGradeTypes>
unitOfMeasures:List<UnitOfMeasure>
identifiers:List<Identifier>
minimumOrderQuantity:Integer
fixedOrderQuantity:Integer
packageQuantity:Integer
itemQuantity:Integer
productPackageType:ProductPackageTypes
}
class SuperSession {
prevPartNames:List<PartName>
newPartNames:List<PartName>
partOrderConfigType:PartOrderConfigTypes
quantity:String
productConsumptionType:ProductConsumptionTypes
warehouses:List<Warehouse>
productStageType:ProductStageTypes
partyIdentifiers:List<PartyIdentifier>
partStatusTypes:List<PartStatusTypes>
}
class UnitOfMeasure {
unitOfMeasure:EnumBase
uomValue:String
quantity:String
uomQuantityCategoryType:UOMQuantityCategoryTypes
}
class AdvanceSearchTypes #FAFF91 {
AI_INFERRED_KEYWORDS
BARCODE_SCANNED_VALUE
FREE_TEXT_SEARCH
NATURAL_LANGUAGE_QUERY
OCR_TEXT
PRODUCT_IMAGE_URL
SEARCH_INTENT_KEYWORDS
WILDCARD_SEARCH_TERM
}
class DurationUOMTypes #FAFF91 {
BI_WEEKS
CUSTOM
DAYS
DAY_OF_MONTH
HOURS
MINUTES
MONTHS
MULTI_YEARS
NONE
OCCURRENCE
OTHER
QUARTERS
SEMI_MONTHS
SEMI_YEARS
UNLIMITED
WEEKS
YEARS
}
class PartConditionGradeTypes #FAFF91 {
ACCEPTABLE
DAMAGED
EXCELLENT
FAIR
GOOD
LIKE_NEW
OTHER
POOR
UNGRADED
VERY_GOOD
}
class PartConditionTypes #FAFF91 {
COLLECTIBLE
DAMAGED_COSMETIC
DAMAGED_MINOR
NEW
NEW_OLD_STOCK
OTHER
REBUILT
REFURBISHED
REMANUFACTURED
SALVAGE
SCRAP
USED
}
class PartIdentifierTypes #FAFF91 {
ALT_CODE
CATALOG_CODE
CONFIG_CODE
COUNTRY_OF_ORIGIN_CODE
ENGINE_CODE
ISBN
MAKE_CODE
MARKET_DIVISION_CODE
MFR_CODE
MODEL_CODE
MPN
NAME
NUMBER
OTHER
PREFIX
PRODUCT_CODE
SKU
STOCK_NBR
STYLE_CODE
SUB_MODEL_CODE
TRANSMISSION_CODE
TRIM_CODE
UNIV_CODE
UPCA
UPCE
VIN
YEAR_CODE
}
class PartInventoryOrderTypes #FAFF91 {
ALLOCATE_RESERVE
BACK_ORDERED
CANCELLED
CONSOLIDATE_INVENTORY
CYCLE_COUNT
DELIVERED
DISPOSITION
INBOUND
LOCATE
MAINTENANCE
NO_LONGER_AVAILABLE
ORDER_FULFILLMENT
OUTBOUND
PENDING
PRE_ORDER
PROCESSING
RECEIVING
RELOCATE
REPLENISH
RETURNED_ORDER
RETURNS_ACTIONS
REVERSE_LOGISTICS
SHIPPED
STOCK_ROTATION
STORAGE
WAREHOUSE_MANAGEMENT
}
class PartNameTypes #FAFF91 {
AFTERMARKET
CORE
GENERIC
MANUFACTURING
MARKETING
OEM
REMANUFACTURING
SUPERSEDED
SUPERSEDING
}
class PartOrderConfigTypes #FAFF91 {
MULTIPLE_MERGE
MULTIPLE_SPLIT
NOT_AVAILABLE
SINGLE
VARIABLE_MERGE
VARIABLE_SPLIT
}
class PartStatusTypes #FAFF91 {
CROSS_DOCK
DISASSEMBLE
DOCUMENT_RECEIPT
DOCUMENT_SHIPMENT
INSPECT_INBOUND
KIT_ASSEMBLE
LABEL_TAG
LOAD_SHIPMENT
PACK
PICK
PUTAWAY
QUARANTINE_INBOUND
RECEIVE
REFURBISH_REPAIR
RETURN_INSPECT
RETURN_PUTAWAY
RETURN_RECEIVE
SCRAP_DISPOSE
SHIP
STAGE_SHIPMENT
SUPERSEDE
SUPERSEDED
VALUE_ADDED_SERVICE
}
class PriceTypes #FAFF91 {
ACTUAL
AFFILIATE
BUNDLE
CONTRACT
CORE
CUSTOM
CUSTOMER
DEALER
DISCOUNT
ESTIMATED
FLAT
ITEMIZED
LANDED
LICENSED
LIST
LOCATION
METERED
MONEY
MSRP
NET
ONLINE
OTHER
PERCENT
PER_UNIT
PROMOTIONAL
PURCHASE
QUANTITY
REGION
RETAIL
SALE
SEAT
STAIR_STEP
STANDARD
STORE
SUBSCRIPTION
TIER_GRADUATED
TIER_VOLUME
TRADE
USAGE
VOLUME
WHOLESALE
}
class ProductConsumptionTypes #FAFF91 {
PRE_PRODUCTION
SCRAP_STRATEGY
USE_UP_STRATEGY
}
class ProductPackageTypes #FAFF91 {
BUNDLE
CASE
COMPONENT
EACH
GROUP
ITEM
KIT
MIXED_BUNDLE
OCCURRENCE
PACK
PALLET
PRODUCT
PURE_BUNDLE
SERVICE
SET
SKU
STANDALONE
SUBSCRIPTION
UNIT
}
class ProductStageTypes #FAFF91 {
ACTIVE
DAMAGED
DECOMMISSIONED
DISCONTINUED
FINAL_SUPERSESSION
OBSOLETE
PENDING_APPROVAL
PENDING_OBSOLESCENCE
PHASED_OUT
PRELIMINARY_SUPERSESSION
PRE_PRODUCTION
PRE_RELEASE
PROPOSED
RECALLED
SOURCING_CHALLENGE
UNDER_REVIEW
}
class ShippingMethodTypes #FAFF91 {
AIR_FREIGHT
CURBSIDE_PICKUP
DOWNLOAD
ECONOMY
ECO_FRIENDLY
EXPRESS
FLAT_RATE
FREE_SHIPPING
FREIGHT
GROUND
HAZMAT
HYBRID_SHIPPING
INTERNATIONAL_EXPEDITED
INTERNATIONAL_STANDARD
LOCAL_DELIVERY
LOCKER_DELIVERY
OCEAN_FREIGHT
OVERNIGHT
PALLET_DELIVERY
PICKUP
RAIL_FREIGHT
SAME_DAY
TABLE_RATE
TEMPERATURE_CONTROLLED
THREE_DAY_SELECT
TWO_DAY_AIR
}
class UOMLengthTypes #FAFF91 {
A
ANGSTROM
CABLE
CENTIMETER
CHAIN
CM
CUBIT
DECIMETER
DEGREE
FATHOM
FEET
FURLONG
HAND
INCH
KILOMETER
KM
LEAGUE
LINK
METER
METER_SYN
MICRON
MILE
MILES
MILLIMETER
MILLI_INCH
MM
NANOMETER
NAUTICAL_MILE
NORMAL_METRIC
PERCH
PIXEL
POLE
ROD
SPAN
VARA
YARD
YOTTAMETER
}
class UOMQuantityCategoryTypes #FAFF91 {
COUNT
DEFAULT_LEAD_TIME
DIMENSIONAL_WEIGHT
DIMENSIONS
DIMENSION_UNIT
ELECTRICAL_RATING
GROSS_VOLUME
GROSS_WEIGHT
MATERIAL
MAX_HEIGHT
MAX_LEAD_TIME
MAX_LENGTH
MAX_ORDER_QUANTITY
MAX_WEIGHT
MAX_WIDTH
MIN_HEIGHT
MIN_LENGTH
MIN_ORDER_AVAILABLE
MIN_ORDER_QUANTITY
MIN_WEIGHT
MIN_WIDTH
NET_VOLUME
NET_WEIGHT
PACKAGE_QUANTITY
SHIPPING_WEIGHT
TIME
VOLUME
WEIGHT
}
class WarehouseTypes #FAFF91 {
ACCESSORY_WAREHOUSE
AFTERMARKET_SUPPLIER
BODY_SHOP_WAREHOUSE
DEALERSHIP
DISTRIBUTOR
IN_HOUSE_PARTS_STORAGE
MOBILE_PARTS_UNIT
NATIONAL_DISTRIBUTION_CENTER
OEM_WAREHOUSE
OTHER
PARTS_SUPPLIER
REGIONAL_DISTRIBUTION_CENTER
RETURN_CORE_CENTER
THIRD_PARTY_LOGISTICS
TIRES_ONLY_DISTRIBUTION
USED_PARTS_YARD
}
class WarrantyTypes #FAFF91 {
CERTIFIED_PRE_OWNED
CORROSION
DEALER
EXTENDED
HYBRID_EV_COMPONENT
LIFETIME
LIMITED
MANUFACTURER
NO_WARRANTY
OTHER
POWERTRAIN
}
AdvanceSearchTypes -- AdvanceSearchValue
AdvanceSearchValue *-- AdvancedSearchCriteria
AdvancedSearchCriteria -- PartSearchCriteria
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- PartLogisticsCriteria
Identifier *-- AdvancedSearchCriteria
Identifier *-- PartIdentifier
Identifier *-- PartLogisticsCriteria
Identifier *-- PartSpecification
PartConditionGradeTypes *-- PartSpecification
PartConditionGradeTypes -- PartSearchCriteria
PartConditionTypes *-- PartSpecification
PartConditionTypes -- PartSearchCriteria
PartIdentifierTypes -- PartIdentifier
PartIdentifier *-- PartSearchCriteria
PartInventoryOrderTypes *-- PartSearchCriteria
PartLifecycle *-- PartSearchCriteria
PartLogisticsCriteria -- PartSearchCriteria
PartNameTypes -- PartName
PartNameTypes -- PartSpecification
PartName *-- PartIdentifier
PartName *-- PartSearchCriteria
PartName *-- SuperSession
PartOrderConfigTypes -- SuperSession
PartPriceCriteria -- PartSearchCriteria
PartSpecification *-- PartSearchCriteria
PartStatusTypes *-- PartLifecycle
PartStatusTypes *-- PartSearchCriteria
PartStatusTypes *-- SuperSession
PriceTypes *-- PartPriceCriteria
ProductConsumptionTypes -- SuperSession
ProductPackageTypes -- PartSpecification
ProductStageTypes *-- AdvancedSearchCriteria
ProductStageTypes *-- PartSearchCriteria
ProductStageTypes -- SuperSession
ShippingMethodTypes *-- PartLogisticsCriteria
SuperSession *-- PartLifecycle
UOMLengthTypes -- PartLogisticsCriteria
UOMQuantityCategoryTypes -- UnitOfMeasure
UnitOfMeasure *-- PartSpecification
WarehouseTypes *-- PartLogisticsCriteria
WarrantyTypes *-- PartPriceCriteria
@enduml
