@startuml
rectangle "Identifier" as Identifier
rectangle "PartIdentifier" as PartIdentifier
rectangle "PartName" as PartName
rectangle "PartPriceCriteria" as PartPriceCriteria
rectangle "PartSearch" as PartSearch
rectangle "PartSearchResult" as PartSearchResult
rectangle "PartConditionTypes" as PartConditionTypes #FAFF91
rectangle "PartIdentifierTypes" as PartIdentifierTypes #FAFF91
rectangle "PartNameTypes" as PartNameTypes #FAFF91
rectangle "PartStatusTypes" as PartStatusTypes #FAFF91
rectangle "PriceTypes" as PriceTypes #FAFF91
rectangle "ShippingMethodTypes" as ShippingMethodTypes #FAFF91
rectangle "WarrantyTypes" as WarrantyTypes #FAFF91
Identifier -- PartSearchResult
Identifier *-- PartIdentifier
Identifier *-- PartSearch
PartConditionTypes -- PartSearchResult
PartIdentifierTypes -- PartIdentifier
PartIdentifier *-- PartSearchResult
PartNameTypes -- PartName
PartName *-- PartIdentifier
PartName *-- PartSearchResult
PartPriceCriteria -- PartSearchResult
PartSearchResult *-- PartSearch
PartStatusTypes -- PartSearchResult
PriceTypes *-- PartPriceCriteria
ShippingMethodTypes *-- PartSearchResult
WarrantyTypes *-- PartPriceCriteria
@enduml
