@startuml
rectangle "AdvanceSearchValue" as AdvanceSearchValue
rectangle "AdvancedSearchCriteria" as AdvancedSearchCriteria
rectangle "EffectivePeriod" as EffectivePeriod
rectangle "Identifier" as Identifier
rectangle "PartIdentifier" as PartIdentifier
rectangle "PartLifecycle" as PartLifecycle
rectangle "PartLogisticsCriteria" as PartLogisticsCriteria
rectangle "PartName" as PartName
rectangle "PartPriceCriteria" as PartPriceCriteria
rectangle "PartSearchCriteria" as PartSearchCriteria
rectangle "PartSpecification" as PartSpecification
rectangle "SuperSession" as SuperSession
rectangle "UnitOfMeasure" as UnitOfMeasure
rectangle "AdvanceSearchTypes" as AdvanceSearchTypes #FAFF91
rectangle "DurationUOMTypes" as DurationUOMTypes #FAFF91
rectangle "PartConditionGradeTypes" as PartConditionGradeTypes #FAFF91
rectangle "PartConditionTypes" as PartConditionTypes #FAFF91
rectangle "PartIdentifierTypes" as PartIdentifierTypes #FAFF91
rectangle "PartInventoryOrderTypes" as PartInventoryOrderTypes #FAFF91
rectangle "PartNameTypes" as PartNameTypes #FAFF91
rectangle "PartOrderConfigTypes" as PartOrderConfigTypes #FAFF91
rectangle "PartStatusTypes" as PartStatusTypes #FAFF91
rectangle "PriceTypes" as PriceTypes #FAFF91
rectangle "ProductConsumptionTypes" as ProductConsumptionTypes #FAFF91
rectangle "ProductPackageTypes" as ProductPackageTypes #FAFF91
rectangle "ProductStageTypes" as ProductStageTypes #FAFF91
rectangle "ShippingMethodTypes" as ShippingMethodTypes #FAFF91
rectangle "UOMLengthTypes" as UOMLengthTypes #FAFF91
rectangle "UOMQuantityCategoryTypes" as UOMQuantityCategoryTypes #FAFF91
rectangle "WarehouseTypes" as WarehouseTypes #FAFF91
rectangle "WarrantyTypes" as WarrantyTypes #FAFF91
AdvanceSearchTypes -- AdvanceSearchValue
AdvanceSearchValue *-- AdvancedSearchCriteria
AdvancedSearchCriteria -- PartSearchCriteria
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- PartLogisticsCriteria
Identifier *-- AdvancedSearchCriteria
Identifier *-- PartIdentifier
Identifier *-- PartLogisticsCriteria
Identifier *-- PartSpecification
PartConditionGradeTypes *-- PartSpecification
PartConditionGradeTypes -- PartSearchCriteria
PartConditionTypes *-- PartSpecification
PartConditionTypes -- PartSearchCriteria
PartIdentifierTypes -- PartIdentifier
PartIdentifier *-- PartSearchCriteria
PartInventoryOrderTypes *-- PartSearchCriteria
PartLifecycle *-- PartSearchCriteria
PartLogisticsCriteria -- PartSearchCriteria
PartNameTypes -- PartName
PartNameTypes -- PartSpecification
PartName *-- PartIdentifier
PartName *-- PartSearchCriteria
PartName *-- SuperSession
PartOrderConfigTypes -- SuperSession
PartPriceCriteria -- PartSearchCriteria
PartSpecification *-- PartSearchCriteria
PartStatusTypes *-- PartLifecycle
PartStatusTypes *-- PartSearchCriteria
PartStatusTypes *-- SuperSession
PriceTypes *-- PartPriceCriteria
ProductConsumptionTypes -- SuperSession
ProductPackageTypes -- PartSpecification
ProductStageTypes *-- AdvancedSearchCriteria
ProductStageTypes *-- PartSearchCriteria
ProductStageTypes -- SuperSession
ShippingMethodTypes *-- PartLogisticsCriteria
SuperSession *-- PartLifecycle
UOMLengthTypes -- PartLogisticsCriteria
UOMQuantityCategoryTypes -- UnitOfMeasure
UnitOfMeasure *-- PartSpecification
WarehouseTypes *-- PartLogisticsCriteria
WarrantyTypes *-- PartPriceCriteria
@enduml
