@startuml
rectangle "Address" as Address
rectangle "AddressLocale" as AddressLocale
rectangle "Authorization" as Authorization
rectangle "Identifier" as Identifier
rectangle "Position" as Position
rectangle "Warehouse" as Warehouse
rectangle "AddressTypes" as AddressTypes #FAFF91
rectangle "LocationTypes" as LocationTypes #FAFF91
rectangle "WarehouseTypes" as WarehouseTypes #FAFF91
AddressLocale *-- Address
AddressTypes *-- Address
Address *-- Warehouse
Authorization *-- Address
Identifier *-- Warehouse
LocationTypes -- AddressLocale
Position -- Address
WarehouseTypes *-- Warehouse
@enduml
