@startuml
class Address {
addressLocales:List<AddressLocale>
priority:String
cityCode:String
addressKey:String
addressId:String
addressInput:String
addressLine1:String
addressLine2:String
addressLine3:String
addressLine4:String
addressLine5:String
addressTypes:List<AddressTypes>
authorizations:List<Authorization>
city:String
citySubdivision:String
country:String
countryCode:String
county:String
countyCode:String
label:String
position:Position
postalCode:String
postalCodeExt:String
preferredIndicator:Boolean
region:String
state:String
locale:String
}
class AddressLocale {
addressLocaleKey:String
addressLocaleId:String
regionCode:String
regionName:String
locationType:LocationTypes
}
class Authorization {
updateDateTime:Date
authorizedIndicator:Boolean
authorizationKey:String
}
class Identifier {
identifierId:String
identifierKey:String
context:String
value:String
detail:String
identifierType:String
}
class Position {
positionId:String
positionKey:String
latitude:String
longitude:String
altitude:String
bearing:String
postalCode:String
}
class Warehouse {
warehouseId:String
warehouseKey:String
warehouseCode:String
warehouseName:String
partyId:String
identifiers:List<Identifier>
warehouseTypes:List<WarehouseTypes>
addresses:List<Address>
}
class AddressTypes #FAFF91 {
ARCHIVE
AR_ADDRESS
BILLING
BUSINESS
CONTRACT
CURRENT
DEALER
DELIVERY
DESTINATION
EMERGENCY
GARAGE
HOME
INSURANCE
LEGAL
MAILING
ORIGINAL
OTHER
POSTAL
PREVIOUS
PRODUCT
REBATE
RECIPIENT
RESIDENCE
SERVICE
SERVICE_CONTRACT
SHIPPING
TEMPORARY
VACATION
WORK
}
class LocationTypes #FAFF91 {
ADDRESS
BOROUGH
BOUNDARY
CITY
COUNTRY
COUNTY
DISTRICT
FEDERAL
GPS
LOCALITY
NO_PREFERENCE
PARISH
POSTAL
PROVINCE
REGION
STATE
STREET
SUB_ADMIN_AREA
SUB_LOCALITY
TELEMATICS
VILLAGE
WAREHOUSE
}
class WarehouseTypes #FAFF91 {
ACCESSORY_WAREHOUSE
AFTERMARKET_SUPPLIER
BODY_SHOP_WAREHOUSE
DEALERSHIP
DISTRIBUTOR
IN_HOUSE_PARTS_STORAGE
MOBILE_PARTS_UNIT
NATIONAL_DISTRIBUTION_CENTER
OEM_WAREHOUSE
OTHER
PARTS_SUPPLIER
REGIONAL_DISTRIBUTION_CENTER
RETURN_CORE_CENTER
THIRD_PARTY_LOGISTICS
TIRES_ONLY_DISTRIBUTION
USED_PARTS_YARD
}
AddressLocale *-- Address
AddressTypes *-- Address
Address *-- Warehouse
Authorization *-- Address
Identifier *-- Warehouse
LocationTypes -- AddressLocale
Position -- Address
WarehouseTypes *-- Warehouse
@enduml
