/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Domain Atlas',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/overview',
        'getting-started/repo-tour',
      ],
    },
    {
      type: 'category',
      label: 'Domains',
      items: [
        {
          type: 'autogenerated',
          dirName: 'domains', // everything under website/docs/domains/**
        },
      ],
    },
    {
      type: 'category',
      label: 'Governance',
      items: [
        {
          type: 'autogenerated',
          dirName: 'governance',
        },
      ],
    },
  ],
};
