@startuml
rectangle "BillOfMaterial" as BillOfMaterial
rectangle "BomComponent" as BomComponent
rectangle "EffectivePeriod" as EffectivePeriod
rectangle "FinancialSplit" as FinancialSplit
rectangle "GeographicBoundary" as GeographicBoundary
rectangle "Identifier" as Identifier
rectangle "LifecycleEvent" as LifecycleEvent
rectangle "Part" as Part
rectangle "PartCategory" as PartCategory
rectangle "PartIdentifier" as PartIdentifier
rectangle "PartInventory" as PartInventory
rectangle "PartInventoryEvent" as PartInventoryEvent
rectangle "PartInventoryMetric" as PartInventoryMetric
rectangle "PartLifecycle" as PartLifecycle
rectangle "PartMaster" as PartMaster
rectangle "PartMasterProfile" as PartMasterProfile
rectangle "PartMasterRegulatory" as PartMasterRegulatory
rectangle "PartName" as PartName
rectangle "PartSpecification" as PartSpecification
rectangle "Party" as Party
rectangle "PartyIdentifier" as PartyIdentifier
rectangle "Price" as Price
rectangle "PricePlan" as PricePlan
rectangle "PriceSensitivity" as PriceSensitivity
rectangle "PriceTier" as PriceTier
rectangle "ProductSchedule" as ProductSchedule
rectangle "SuperSession" as SuperSession
rectangle "TextualDetail" as TextualDetail
rectangle "UnitOfMeasure" as UnitOfMeasure
rectangle "DurationUOMTypes" as DurationUOMTypes #FAFF91
rectangle "FinancialTransactionTypes" as FinancialTransactionTypes #FAFF91
rectangle "HazardClassTypes" as HazardClassTypes #FAFF91
rectangle "InventoryStatusTypes" as InventoryStatusTypes #FAFF91
rectangle "LedgerActionTypes" as LedgerActionTypes #FAFF91
rectangle "LifecycleEventTypes" as LifecycleEventTypes #FAFF91
rectangle "LocationTypes" as LocationTypes #FAFF91
rectangle "NarrativeUomTypes" as NarrativeUomTypes #FAFF91
rectangle "PartConditionGradeTypes" as PartConditionGradeTypes #FAFF91
rectangle "PartConditionTypes" as PartConditionTypes #FAFF91
rectangle "PartHazardPackingGroupTypes" as PartHazardPackingGroupTypes #FAFF91
rectangle "PartIdentifierTypes" as PartIdentifierTypes #FAFF91
rectangle "PartInventoryMetricTypes" as PartInventoryMetricTypes #FAFF91
rectangle "PartInventoryOrderTypes" as PartInventoryOrderTypes #FAFF91
rectangle "PartNameTypes" as PartNameTypes #FAFF91
rectangle "PartOrderConfigTypes" as PartOrderConfigTypes #FAFF91
rectangle "PartStatusTypes" as PartStatusTypes #FAFF91
rectangle "PartyRelationshipTypes" as PartyRelationshipTypes #FAFF91
rectangle "PartyServiceTypes" as PartyServiceTypes #FAFF91
rectangle "PartyTypes" as PartyTypes #FAFF91
rectangle "PayeeTypes" as PayeeTypes #FAFF91
rectangle "PaymentCategoryTypes" as PaymentCategoryTypes #FAFF91
rectangle "PriceClassTypes" as PriceClassTypes #FAFF91
rectangle "PriceSensitivityTypes" as PriceSensitivityTypes #FAFF91
rectangle "PriceTypes" as PriceTypes #FAFF91
rectangle "ProductConsumptionTypes" as ProductConsumptionTypes #FAFF91
rectangle "ProductPackageTypes" as ProductPackageTypes #FAFF91
rectangle "ProductPriceItemTypes" as ProductPriceItemTypes #FAFF91
rectangle "ProductStageTypes" as ProductStageTypes #FAFF91
rectangle "ProductStatusTypes" as ProductStatusTypes #FAFF91
rectangle "SalesStatusTypes" as SalesStatusTypes #FAFF91
rectangle "ScheduleTypes" as ScheduleTypes #FAFF91
rectangle "UOMQuantityCategoryTypes" as UOMQuantityCategoryTypes #FAFF91
rectangle "UnitOfMeasureTypes" as UnitOfMeasureTypes #FAFF91
BillOfMaterial -- PartMaster
BomComponent *-- BillOfMaterial
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- BomComponent
EffectivePeriod -- PartyIdentifier
EffectivePeriod -- ProductSchedule
FinancialSplit *-- PricePlan
FinancialTransactionTypes -- FinancialSplit
GeographicBoundary *-- PricePlan
GeographicBoundary *-- ProductSchedule
HazardClassTypes *-- PartMasterRegulatory
Identifier *-- Part
Identifier *-- PartIdentifier
Identifier *-- PartInventory
Identifier *-- PartMaster
Identifier *-- PartMasterProfile
Identifier *-- PartSpecification
Identifier *-- Party
Identifier *-- TextualDetail
InventoryStatusTypes -- PartInventory
LedgerActionTypes -- FinancialSplit
LifecycleEventTypes -- LifecycleEvent
LifecycleEventTypes -- PartMaster
LifecycleEventTypes -- PricePlan
LifecycleEvent *-- PricePlan
LocationTypes -- GeographicBoundary
NarrativeUomTypes -- ProductSchedule
PartCategory *-- PartMaster
PartConditionGradeTypes *-- PartSpecification
PartConditionGradeTypes -- Part
PartConditionTypes *-- PartSpecification
PartConditionTypes -- Part
PartHazardPackingGroupTypes -- PartMasterRegulatory
PartIdentifierTypes -- PartIdentifier
PartIdentifier *-- BillOfMaterial
PartIdentifier *-- BomComponent
PartIdentifier *-- Part
PartIdentifier *-- PartInventory
PartIdentifier *-- PartMaster
PartInventory *-- PartMaster
PartInventoryEvent *-- PartInventory
PartInventoryMetricTypes -- PartInventoryMetric
PartInventoryMetric *-- PartInventory
PartInventoryOrderTypes -- PartInventoryEvent
PartLifecycle *-- Part
PartLifecycle *-- PartMaster
PartMasterProfile -- PartMaster
PartMasterRegulatory -- PartMaster
PartNameTypes -- PartName
PartNameTypes -- PartSpecification
PartName *-- PartIdentifier
PartName *-- PartMaster
PartName *-- SuperSession
PartOrderConfigTypes -- SuperSession
PartSpecification -- BillOfMaterial
PartSpecification -- BomComponent
PartSpecification *-- PartMasterProfile
PartStatusTypes *-- Part
PartStatusTypes *-- PartLifecycle
PartStatusTypes *-- SuperSession
PartStatusTypes -- Part
Part *-- PartInventory
Party -- PartyIdentifier
PartyIdentifier *-- PartMaster
PartyIdentifier *-- PricePlan
PartyIdentifier *-- SuperSession
PartyRelationshipTypes *-- PartyIdentifier
PartyServiceTypes *-- Party
PartyTypes *-- Party
PayeeTypes -- PriceTier
PaymentCategoryTypes -- PriceTier
Price -- FinancialSplit
PriceClassTypes *-- PricePlan
PriceClassTypes *-- PriceTier
PricePlan *-- PartMaster
PriceSensitivity -- PricePlan
PriceSensitivity -- PriceTier
PriceSensitivityTypes -- PriceSensitivity
PriceTier *-- PricePlan
PriceTypes *-- Price
PriceTypes *-- PricePlan
Price *-- Part
Price *-- PartInventory
ProductConsumptionTypes -- SuperSession
ProductPackageTypes -- PartSpecification
ProductPriceItemTypes -- FinancialSplit
ProductSchedule *-- PricePlan
ProductStageTypes -- PartMaster
ProductStageTypes -- SuperSession
ProductStatusTypes -- BillOfMaterial
ProductStatusTypes -- BomComponent
SalesStatusTypes -- PartMasterProfile
ScheduleTypes -- ProductSchedule
SuperSession *-- PartLifecycle
TextualDetail *-- BomComponent
TextualDetail *-- PartCategory
TextualDetail *-- PartMaster
UOMQuantityCategoryTypes -- UnitOfMeasure
UnitOfMeasureTypes -- GeographicBoundary
UnitOfMeasure *-- PartMaster
UnitOfMeasure *-- PartSpecification
@enduml
