@startuml
rectangle "ControlAccount" as ControlAccount
rectangle "Identifier" as Identifier
rectangle "Part" as Part
rectangle "PartEvent" as PartEvent
rectangle "PartIdentifier" as PartIdentifier
rectangle "PartInventory" as PartInventory
rectangle "PartInventoryEvent" as PartInventoryEvent
rectangle "PartInventoryMetric" as PartInventoryMetric
rectangle "PartLifecycle" as PartLifecycle
rectangle "PartLocation" as PartLocation
rectangle "PartName" as PartName
rectangle "Price" as Price
rectangle "Warehouse" as Warehouse
rectangle "ControlAccountRoleTypes" as ControlAccountRoleTypes #FAFF91
rectangle "ControlAccountTypes" as ControlAccountTypes #FAFF91
rectangle "FinancialCategoryTypes" as FinancialCategoryTypes #FAFF91
rectangle "InventoryStatusTypes" as InventoryStatusTypes #FAFF91
rectangle "PartConditionGradeTypes" as PartConditionGradeTypes #FAFF91
rectangle "PartConditionTypes" as PartConditionTypes #FAFF91
rectangle "PartIdentifierTypes" as PartIdentifierTypes #FAFF91
rectangle "PartInventoryMetricTypes" as PartInventoryMetricTypes #FAFF91
rectangle "PartInventoryOrderTypes" as PartInventoryOrderTypes #FAFF91
rectangle "PartNameTypes" as PartNameTypes #FAFF91
rectangle "PartStatusTypes" as PartStatusTypes #FAFF91
rectangle "PartStorageTypes" as PartStorageTypes #FAFF91
rectangle "PriceTypes" as PriceTypes #FAFF91
rectangle "WarehouseTypes" as WarehouseTypes #FAFF91
ControlAccount -- Part
ControlAccountRoleTypes -- ControlAccount
ControlAccountTypes -- ControlAccount
FinancialCategoryTypes -- ControlAccount
Identifier *-- ControlAccount
Identifier *-- Part
Identifier *-- PartIdentifier
Identifier *-- PartInventory
Identifier *-- Warehouse
InventoryStatusTypes -- PartInventory
PartConditionGradeTypes -- Part
PartConditionTypes -- Part
PartEvent *-- Part
PartIdentifierTypes -- PartIdentifier
PartIdentifier *-- Part
PartIdentifier *-- PartInventory
PartInventoryEvent *-- PartInventory
PartInventoryMetricTypes -- PartInventoryMetric
PartInventoryMetric *-- PartInventory
PartInventoryOrderTypes -- PartEvent
PartInventoryOrderTypes -- PartInventoryEvent
PartLifecycle *-- Part
PartLocation -- Part
PartNameTypes -- PartName
PartName *-- PartIdentifier
PartStatusTypes *-- Part
PartStatusTypes *-- PartLifecycle
PartStatusTypes -- Part
PartStatusTypes -- PartEvent
PartStorageTypes -- PartLocation
Part *-- PartInventory
PriceTypes *-- Price
Price *-- Part
Price *-- PartInventory
Warehouse -- Part
Warehouse -- PartLocation
WarehouseTypes *-- Warehouse
@enduml
